version: '3'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000" # grafana frontend
    restart: always
    volumes:
      - ${GRAFANA_VOLUME_ROOT}/var/lib/grafana:/var/lib/grafana
    networks:
      - graphite_collect_and_report

networks:
  graphite_collect_and_report:
    external: true
