version: '3'

services:
  graphite:
    image: graphite
    build: .
    container_name: graphite
    restart: always
    networks:
      - collect_and_report
    volumes:
      - ${GRAPHITE_VOLUME_ROOT}/data/whisper:/opt/graphite/storage/whisper
      - ${GRAPHITE_VOLUME_ROOT}/log/graphite:/opt/graphite/storage/log
    environment:
      ALLOWED_HOSTS: grafana
    ports:
      - "2003-2004:2003-2004" # carbon receivers
      - "8125:8125" # statsd
      - "${GRAPHITE_PORT}:80" # web iface for grafana use

networks:
  collect_and_report:
    driver: bridge
