version: '3'

services:
  graphite:
    image: hopsoft/graphite-statsd
    container_name: graphite
    restart: always
    networks:
      - backend_bridge
    volumes:
      - ./graphite_volume/data/whisper:/opt/graphite/storage/whisper
      - ./graphite_volume/log/graphite:/opt/graphite/storage/log
    environment:
      ALLOWED_HOSTS: grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000" # grafana frontend
    restart: always
    volumes:
      - ./grafana_volume/var/lib/grafana:/var/lib/grafana
    networks:
      - backend_bridge

networks:
  backend_bridge:
    driver: bridge
